# application 파일 (확장자.properties. yml 동일)
#애플리케이션의 설정 정보를 관리하는 파일

#파일의 역활 및 용도
#1 애플리케이션 서번 환경 설정= 서버 포트 번호 등을 관리
#2 데이터베이스 설정 url ,사용자명 , 비밍번호 등을 정의
#jpa 및 hibernate 설정
# - DB와 상호 작용시 엔티티 매핑 방식과 sql출력 여부등의 우선 적용

#동작 방식
# .properties와 yml이 모두 존재할 경우 -properties가 우선 적용

#properties vs yml
#1.properties
#: 주로 설정이 단순하거나 개발 초기 단계에서 사용
#2.yml
#설정이 복잡하고 중첩된 구조가 필요할때 선호

#3. 형식 및 구조 차이
#.properties
# -키- 값 쌍의 형태로 결정
#게층적(들여쓰기) 구조를 사용
#거독성이 졸고 복잡한 설정을 쉽게  관리
server:
  port: 8080
  #Spring Boot와 JPA를 이용해ORM을 구현
  #애플리케이션 설정에서 연결할 DB를명시
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_db
    username: root
    password: zkzk0209

#  profiles:
#    active:
#      -dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true